name: Deploy React App to DSM

on:
  push:
    branches: ["main"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Deploy to DSM via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.SERVER_PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            git config --global --add safe.directory /volume1/docker/portfolio
            cd /volume1/docker/portfolio
            git reset --hard
            git pull origin main
            /usr/local/bin/docker-compose down
            /usr/local/bin/docker-compose up -d --build